---
title: "Data prep"
author: "BVD"
date: "6/23/2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Load data
```{r message=FALSE}
load("~/DFW7_1_19.RData")
DFW<-DFW7_1_19

library("cAIC4")
library("MuMIn")
library("lme4")
library("dummies")
library(foreach)
library(ggplot2)
library(multcomp)
library("dplyr")
```

```{r}
logit2prob <- function(logit){
  odds <- exp(logit)
  prob <- odds / (1 + odds)
  return(prob)
}

model_probs <- function(courses){
probcourses <- summary(courses)

temp <- data.frame(group=rownames(probcourses$linfct),
             q = probcourses$test$coefficients, 
             se = (probcourses$test$sigma))

temp$UL <- temp$q+temp$se
temp$LL <- temp$q-temp$se
temp2 <- logit2prob(temp[c(2,4,5)])
return <- temp2
}
```

ID LA courses
```{r}
DFW$LA<-0
DFW$LA[
  DFW$INSTRUCTOR1_NAME=="Brookes,David T" & DFW$Number=="202A" & DFW$TERM=="2172" | 
         DFW$INSTRUCTOR1_NAME=="Brookes,David T" & DFW$Number=="202A" & DFW$TERM=="2178" | 
         DFW$INSTRUCTOR1_NAME=="Brookes,David T" & DFW$Number=="202A" & DFW$TERM=="2182" | 
         DFW$INSTRUCTOR1_NAME=="Brookes,David T" & DFW$Number=="202A" & DFW$TERM=="2188" | 
         DFW$INSTRUCTOR1_NAME=="Brookes,David T" & DFW$Number=="202A" & DFW$TERM=="2192" | 
         DFW$INSTRUCTOR1_NAME=="Brookes,David T" & DFW$Number=="202B" & DFW$TERM=="2168" |
         DFW$INSTRUCTOR1_NAME=="Arpin,Paul C" & DFW$Number=="204B" & DFW$TERM=="2172" | 
         DFW$INSTRUCTOR1_NAME=="Arpin,Paul C" & DFW$Number=="204B" & DFW$TERM=="2178" | 
         DFW$INSTRUCTOR1_NAME=="Arpin,Paul C" & DFW$Number=="204B" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Arpin,Paul C" & DFW$Number=="204A" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Arpin,Paul C" & DFW$Number=="202B" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Ayars,Eric J" & DFW$Number=="204A" & DFW$TERM=="2172" |
    DFW$INSTRUCTOR1_NAME=="Ayars,Eric J" & DFW$Number=="204A" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Ayars,Eric J" & DFW$Number=="204A" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="118" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="118" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="119" & DFW$TERM=="2168" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="119" & DFW$TERM=="2172" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="119" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="119" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="119" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Bailey,Paul L" & DFW$Number=="120" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Danner,Richard S" & DFW$Number=="118" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Danner,Richard S" & DFW$Number=="120" & DFW$TERM=="2172" |
    DFW$INSTRUCTOR1_NAME=="Danner,Richard S" & DFW$Number=="118" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Herrera,Christine A" & DFW$Number=="120" & DFW$TERM=="2172" |
    DFW$INSTRUCTOR1_NAME=="Herrera,Christine A" & DFW$Number=="120" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Herrera,Christine A" & DFW$Number=="120" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Herrera,Christine A" & DFW$Number=="120" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Lin,Yuhfen" & DFW$Number=="202A" & DFW$TERM=="2168" |
    DFW$INSTRUCTOR1_NAME=="Lin,Yuhfen" & DFW$Number=="202A" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Lin,Yuhfen" & DFW$Number=="202A" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Lin,Yuhfen" & DFW$Number=="202B" & DFW$TERM=="2172" |
    DFW$INSTRUCTOR1_NAME=="Lin,Yuhfen" & DFW$Number=="202B" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Lin,Yuhfen" & DFW$Number=="202B" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Lin,Yuhfen" & DFW$Number=="204B" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Newton,Mark H" & DFW$Number=="343" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Newton,Mark H" & DFW$Number=="343" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Pechkis,Hyewon K" & DFW$Number=="204B" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Pechkis,Hyewon K" & DFW$Number=="204B" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Pechkis,Hyewon K" & DFW$Number=="204B" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Petrova-Mayor,Anna I" & DFW$Number=="204A" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Petrova-Mayor,Anna I" & DFW$Number=="204C" & DFW$TERM=="2172" |
    DFW$INSTRUCTOR1_NAME=="Petrova-Mayor,Anna I" & DFW$Number=="204C" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Petrova-Mayor,Anna I" & DFW$Number=="204C" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Strand,Krista L" & DFW$Number=="110" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Strand,Krista L" & DFW$Number=="110" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Tran,Cawa" & DFW$Number=="153" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Tran,Cawa" & DFW$Number=="153" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="141" & DFW$TERM=="2168" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="141" & DFW$TERM=="2172" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="141" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="141" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="141" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="141" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="321" & DFW$TERM=="2178" |
    DFW$INSTRUCTOR1_NAME=="Van Dusen,Benjamin C" & DFW$Number=="350" & DFW$TERM=="2182" |
    DFW$INSTRUCTOR1_NAME=="Zou,Xueli" & DFW$Number=="204A" & DFW$TERM=="2188" |
    DFW$INSTRUCTOR1_NAME=="Zou,Xueli" & DFW$Number=="204A" & DFW$TERM=="2192" |
    DFW$INSTRUCTOR1_NAME=="Pechkis,Joseph A" & DFW$Number=="202B" & DFW$TERM=="2192"
         ] <- 1

```

variables I care about
```{r}
DFW <- DFW[!is.na(DFW$Grade_Group),]
#DFW$DFW<-ifelse(DFW$Grade_Group=="A",0,ifelse(DFW$Grade_Group=="B",0,ifelse(DFW$Grade_Group=="C",0,ifelse(DFW$Grade_Group=="D",0,ifelse(DFW$Grade_Group=="CR",0,1)))))
DFW$DDFW<-ifelse(DFW$Grade_Group=="A",0,ifelse(DFW$Grade_Group=="B",0,ifelse(DFW$Grade_Group=="C",0,ifelse(DFW$Grade_Group=="CR",0,1))))
names(DFW)[names(DFW)=="INSTRUCTOR1_NAME"] <- "instructor"
names(DFW)[names(DFW)=="FirstGeneration"] <- "firstgen"
names(DFW)[names(DFW)=="COURSE_ID"] <- "course"
names(DFW)[names(DFW)=="Ethnicity"] <- "race"
names(DFW)[names(DFW)=="GenderLabel"] <- "gender"
DFW$courID <- paste(DFW$Subject,DFW$course,DFW$Section,DFW$TERM, sep='')

reduced <- as.data.frame(dplyr::select(DFW, TERM, Subject, Number,courID, Section, instructor,firstgen, gender, race, dependent_income, LA, DDFW))

```

creating dummy variables
```{r}
reduced <- dummy.data.frame(reduced, names=c("Number","race","firstgen","gender"),sep = "_")
reduced <- cbind(reduced, dplyr::select(DFW, "Number","race","firstgen","gender"))

reduced$nonwhite <- ifelse(reduced$race=="White",0,1)
reduced$algebra <- ifelse(reduced$Number=="202A" |DFW$Number=="202B",1,0)
reduced$Female <- ifelse(reduced$gender=="Male",0,1)
reduced$firstgen <- ifelse(reduced$firstgen=="First Generation Student",1,0)
```

subset data
```{r}
red_phys <- reduced[reduced$Subject=="PHYS",]
red_math <- reduced[reduced$Subject=="MATH",]
red_math_phys <- reduced[reduced$Subject=="PHYS" | reduced$Subject=="MATH",]
red_202A <- reduced[reduced$Number=="202A",]
red_202B <- reduced[reduced$Number=="202B",]
red_204A <- reduced[reduced$Number=="204A",]
red_204B <- reduced[reduced$Number=="204B",]
red_204C <- reduced[reduced$Number=="204C",]
red_introPhys <- reduced[reduced$Number=="204A" | reduced$Number=="202A",]
red_202_204 <- reduced[reduced$Number=="204A" | reduced$Number=="204B" | reduced$Number=="204C" | reduced$Number=="202A" | reduced$Number=="202B",]
```

Find best model (intro physics) (https://quantscience.rbind.io/2017/12/26/model-selection-for-multilevel-modeling/)
```{r}
#m_all <- (DDFW ~ firstgen*LA + Female*LA + nonwhite*LA + algebra*LA + (1|courID))
m_all <- (DDFW ~ firstgen*LA*Female*nonwhite + algebra + (1|courID))
options(na.action = "na.fail")
intro_mod_dredge <- glmer(m_all, data=red_introPhys,family = binomial)
intro_dredge <- dredge(intro_mod_dredge)
model.sel(intro_dredge, rank=AIC)
```

Find best model (between classes) (https://quantscience.rbind.io/2017/12/26/model-selection-for-multilevel-modeling/)
```{r}
m_courses <- (DDFW ~ Number_204B*LA + Number_204C*LA + Number_202A*LA + Number_202B*LA + (1|courID))
options(na.action = "na.fail")
phys_mod_dredge <- glmer(m_courses, data=red_202_204,family = binomial)
phys_dredge <- dredge(phys_mod_dredge)
model.sel(phys_dredge, rank=AIC)
```

running best model - intro phys
```{r}
intro_mod_uncond <- (DDFW ~ + (1|courID))
intro_m_uncond <- glmer(intro_mod_uncond, data=red_introPhys,family = binomial)

intro_mod_final <- (DDFW ~ firstgen*LA + Female*LA + nonwhite*LA + firstgen*nonwhite + (1|courID))
intro_m_final <- glmer(intro_mod_final, data=red_introPhys,family = binomial)
summary(intro_m_uncond)
summary(intro_m_final)
ICC <- 0.3102/(0.3102+pi^2/3)
```

running best model - physics
```{r}
phys_mod_final <- (DDFW ~ Number_204B*LA + Number_204C*LA + Number_202A*LA + Number_202B*LA + (1|courID))
phys_m_final <- glmer(phys_mod_final, data=red_202_204,family = binomial)
summary(phys_m_final)
```

Logits
```{r}
#courses
#(Int, 204B,LA,204C, 202A,202B,204B:LA ,204C:LA,202A:LA,202B:LA)
p204A=    c(1, 0,0,0, 0,0,0, 0,0,0)
p204ALA=  c(1, 0,1,0, 0,0,0, 0,0,0)
p204B=    c(1, 1,0,0, 0,0,0, 0,0,0)
p204BLA=  c(1, 1,1,0, 0,0,1, 0,0,0)
p204C=    c(1, 0,0,1, 0,0,0, 0,0,0)
p204CLA=  c(1, 0,1,1, 0,0,0, 1,0,0)
p202A=    c(1, 0,0,0, 1,0,0, 0,0,0)
p202ALA=  c(1, 0,1,0, 1,0,0, 0,1,0)
p202B=    c(1, 0,0,0, 0,1,0, 0,0,0)
p202BLA=  c(1, 0,1,0, 0,1,0, 0,0,1)

contrast_forms_course <- rbind ('p204A'=p204A,
                                'p204A LA'=p204ALA,
                                'p204B'=p204B,
                                'p204B LA'=p204BLA,
                                'p204C'=p204C,
                                'p204C LA'=p204CLA,                                
                                'p202A'=p202A,
                                'p202A LA'=p202ALA,
                                'p202B'=p202B,
                                'p202B LA'=p202BLA)

names(contrast_forms_course) <- c("Number_204B", "LA", "Number_204C", "Number_202A", "Number_202B", "Nmb_204B:LA", "LA:Nmb_204C", "LA:Nmb_202A", "LA:Nmb_202B")

courses <- glht(phys_m_final, contrast_forms_course)

#Students
#(Int, fg,LA,fem,nwhi, fg:LA,fem:LA,nwhi:LA, fg:nwhi)
WMR =   c(1, 0,0,0,0, 0,0,0, 0) #White, male, returning, no LA
WMRL =  c(1, 0,1,0,0, 0,0,0, 0) #White, male, returning, LA
BMR =   c(1, 0,0,0,1, 0,0,0, 0) 
BMRL =  c(1, 0,1,0,1, 0,0,1, 0)
WFR =   c(1, 0,0,1,0, 0,0,0, 0) 
WFRL =  c(1, 0,1,1,0, 0,1,0, 0)
WMF =   c(1, 1,0,0,0, 0,0,0, 0) 
WMFL =  c(1, 1,1,0,0, 1,0,0, 0)
WFF =   c(1, 1,0,1,0, 0,0,0, 0) 
WFFL =  c(1, 1,1,1,0, 1,1,0, 0)
BFR =   c(1, 0,0,1,1, 0,0,0, 0) 
BFRL =  c(1, 0,1,1,1, 0,1,1, 0)
BMF =   c(1, 1,0,0,1, 0,0,0, 1) 
BMFL =  c(1, 1,1,0,1, 1,0,1, 1)
BWF =   c(1, 1,0,1,1, 0,0,0, 1) 
BWFL =  c(1, 1,1,1,1, 1,1,1, 1)

contrast_forms_students <- rbind ('White male'=WMR,
                                'White male with LA'=WMRL,
                                'White female'=WFR,
                                'White female LA'=WFRL,                                
                                'Non-White male'=BMR,
                                'Non-White male LA'=BMRL,
                                'Non-White female'=BFR,
                                'Non-White female LA'=BFRL,
                                'White male first-gen'=WMF,
                                'White male first-gen LA'=WMFL,
                                'White female first-gen'=WFF,
                                'White female first-gen LA'=WFFL,
                                'Non-White male first-gen'=BMF,
                                'Non-White male first-gen LA'=BMFL,
                                'Non-White female first-gen'=BWF,
                                'Non-White female first-gen LA'=BWFL)

names(contrast_forms_course) <- c("Number_204B", "LA", "Number_204C", "Number_202A", "Number_202B", "Nmb_204B:LA", "LA:Nmb_204C", "LA:Nmb_202A", "LA:Nmb_202B")

students <- glht(intro_m_final, contrast_forms_students)

```

Probabilities (https://sebastiansauer.github.io/convert_logit2prob/)
```{r}
phys_courses_prob <- model_probs(courses)
phys_students_prob <- model_probs(students)
```

```{r}
#phys_students_prob$race <- factor(contrast_p6_est$race, levels = c("Black", "Hispanic", "Island", "Other", "Asian",    "White"))


phys_courses_prob$course <- factor(c("204A", "204A", "204B", "204B", "204C", "204C", "202A", "202A", "202B", "202B"))
phys_courses_prob$instruction <- factor(c("Traditional", "LA", "Traditional", "LA", "Traditional", "LA", "Traditional", "LA", "Traditional", "LA"))

courseplot <- ggplot(phys_courses_prob, aes(x=course, y=q, fill=instruction)) + geom_bar(stat = "identity", position= "dodge") + geom_errorbar(aes( ymax= UL, ymin=LL), position="dodge") +
  theme(legend.position = "bottom", axis.title.x=element_blank(), axis.text.x=element_text(angle=90), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  ylab("DFW probability")

plot(courseplot)
#qplot(course, q, phys_courses_prob, aes(x=course, y=q), geom="bar")


phys_students_prob$demo <- factor(c("White Male", "White Male", "White Female", "White Female", "Non-White Male", "Non-White Male", "Non-White Female", "Non-White Female", "White Male", "White Male", "White Female", "White Female", "Non-White Male", "Non-White Male", "Non-White Female", "Non-White Female"))
phys_students_prob$Race <- factor(c("White", "White", "White", "White", "Non-White", "Non-White", "Non-White", "Non-White", "White", "White", "White", "White", "Non-White", "Non-White", "Non-White", "Non-White"))
phys_students_prob$instruction <- factor(c("traditional", "LA", "traditional", "LA", "traditional", "LA", "traditional", "LA", "traditional", "LA", "traditional", "LA", "traditional", "LA", "traditional", "LA"))
phys_students_prob$firstgen <- factor(c("non-firstgen", "non-firstgen", "non-firstgen", "non-firstgen", "non-firstgen", "non-firstgen", "non-firstgen", "non-firstgen", "firstgen", "firstgen", "firstgen", "firstgen", "firstgen", "firstgen", "firstgen", "firstgen"))

studentplot <- ggplot(phys_students_prob, aes(x=demo, y=q, fill=instruction)) + geom_bar(stat = "identity", position= "dodge") + geom_errorbar(aes( ymax= UL, ymin=LL), position="dodge") +
  theme(legend.position = "bottom", axis.title.x=element_blank(), axis.text.x=element_text(angle=90), axis.ticks.x=element_blank(),panel.grid.major = element_blank(), panel.grid.minor = element_blank(),panel.background = element_blank(), axis.line = element_line(colour = "black"),text = element_text(size=16, color = "black")) +
  ylab("DFW probability") +
facet_grid(.~firstgen, scales = "free", space = "free")

plot(studentplot)

```


